---
#Configures real servers on alteon loadbalancer using user input
- name: "Starting real server configuration service on alteon loadbalancer"
  hosts: loadbalancer
  connection: local
  gather_facts: false

  tasks:
    - name: "Configure server module"
      radware.radware_modules.alteon_config_server:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ alteon_username }}"
          password: "{{ alteon_password }}"
          validate_certs: no
          https_port: 8443
          ssh_port: 22
          timeout: 5
        state: present
        parameters:
          index: "{{ real_index }}"
          state: "{{ real_state }}"
          ip_address: "{{ real_ip_address }}"
          name: "{{ real_name }}"

